### PR TITLE
Style improvements to README

### PR DESCRIPTION
**Pull request by raiyaj**
Tidy up grammar, and improve flow and conciseness of README.

### CODE REVIEW

**Comment by spences10** [comment]
Thanks for your contribution @raiyaj 👍

**Comment by raiyaj** [comment]
No worries, thanks for making great tutorials! Would it be possible to merge?

**Comment by spences10** [comment]
Don't know about merging as I'm not sure I like what you have done with it and I'm probably going to do something different with this as it is anyway.

I'm going to leave it open for now to come back to when I have the capacity to work on this, but right now this isn't my main focus.

I'm sure you understand, thanks 🦄

**Comment by spences10** [comment]
@raiyaj have you seen the [freeCodeCamp guides] site?

What I would like to do is have something like that which will help for searching and close https://github.com/spences10/twitter-bot-playground/issues/30

It uses my current fave framework [Gatsby] for static site gen, you have any experience with it?

[freecodecamp guides]: https://guide.freecodecamp.org/
[gatsby]: http://gatsbyjs.org/

**Pull request closed without merging**
